### ISSUE TITLE
Other ways to install after trouble installing with the readme guide.

### ISSUE THREAD

**Issue by KiriCattus** [alex47/BreezeBlurred#12]
Can this be installed using apt-get rather than the way provided in the readme as I have had trouble installing it that way on the ``cmake`` step and I'm not sure what this all means sadly.
I got the error below and have at least given a link to the log on gist to try and help assist a little.

OS: Debian 9
[Gist - CMakeOutput.log](https://gist.github.com/ProxyNeko/fd65d9b79a00efd6fa6ffdecf634ca2f)
```
proxyneko@catbox ~/D/B/build> cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
CMake Error at CMakeLists.txt:11 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 0.0.9) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/proxyneko/Documents/BreezeBlurred/build/CMakeFiles/CMakeOutput.log".
```

If you need any more info just ask.

**Comment by alex47** [comment]
did you install the dependencies?
https://github.com/alex47/BreezeBlurred#ubuntu-kde-neon

**Comment by KiriCattus** [comment]
I thought I had done but I ran it again anyway to make sure and new things installed but to double check, is this fine?
```
proxyneko@catbox ~/D/B/build> cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Found FFTW: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/proxyneko/Downloads/BreezeBlurred/build
```

**Comment by alex47** [comment]
I think it should be fine
try installing it now

**Comment by KiriCattus** [comment]
Seems to have worked now :/ Sorry to bring such a silly issue to you but thank you for the pointers.
Next time I'll double check things

**Comment by alex47** [comment]
glad it worked out
