### ISSUE TITLE
how to uninstall it

### ISSUE THREAD

**Issue by Asutorufa** [alex47/BreezeBlurred#16]
i am installed it,but it cant running in the back-end. now i want to uninstall it,but i cant run ```sudo make uninstall```
```
CMake Error at CMakeLists.txt:21 (find_package):
  By not providing "FindKDecoration2.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KDecoration2", but CMake did not find one.

  Could not find a package configuration file provided by "KDecoration2" with
  any of the following names:

    KDecoration2Config.cmake
    kdecoration2-config.cmake

  Add the installation prefix of "KDecoration2" to CMAKE_PREFIX_PATH or set
  "KDecoration2_DIR" to a directory containing one of the above files.  If
  "KDecoration2" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by d2weber** [comment]
Apparently you did not configure the CMAKE_PREFIX_PATH. To uninstall first run the commands in the installation section of the README.md. Especially

    cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF -DKDE_INSTALL_USE_QT_SYS_PATHS=ON

Afterwards `sudo make uninstall` should work.

**Comment by Asutorufa** [comment]
> Apparently you did not configure the CMAKE_PREFIX_PATH. To uninstall first run the commands in the installation section of the README.md. Especially
> 
> ```
> cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
> ```
> 
> Afterwards `sudo make uninstall` should work.

Thank you so much.
