### ISSUE TITLE
Cannot find qmake

### ISSUE THREAD

**Issue by Astilex5** [alex47/BreezeBlurred#21]
I am trying to install this on Solus Linux. However qmake cannot be found.

However, I have found qmake at `/usr/bin/qmake` So I am not sure what is going on.

This command:

`cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF -DKDE_INSTALL_USE_QT_SYS_PATHS=ON`

Prints out:

CMake Error at /usr/share/ECM/modules/ECMQueryQmake.cmake:30 (message):
  No qmake Qt5 binary found.  Can't check QT_INSTALL_PLUGINS as required
Call Stack (most recent call first):
  /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:483 (query_qmake)
  CMakeLists.txt:15 (include)

**Comment by ghost** [comment]
Sorry for the necropost, I'm in the same exact position right now.

Did you find a solution?
