### ISSUE TITLE
Nice work -- and feature request: opacity scale in percents

### ISSUE THREAD

**Issue by tsujan** [alex47/BreezeBlurred#4]
Thanks for this nice work!

It's the best KDE title-bar for Kvantum but in a scale from 0 to 100 (× 2.55) because Kvantum's window opacity can be changed by users in terms of percents:

![opacity](https://user-images.githubusercontent.com/981076/42738858-4f50f098-88a0-11e8-8e3d-13ed0a9f8309.png)

In the above screenshot, I changed the scale in your code, so that: page-step = 10, single-step = 1, max = 100 (a log-out and log-in was needed because of KDE's cache)

Is that acceptable to you and would you do the same thing here?

**Comment by alex47** [comment]
Done
How is it now: https://i.imgur.com/Q65LKZZ.gifv

**Comment by tsujan** [comment]
Much better than what I did here :) Thank you very much!
