### ISSUE TITLE
A problem inherited from Breeze

### ISSUE THREAD

**Issue by tsujan** [alex47/BreezeBlurred#5]
Breeze's title-bar gradient starts at 0.0 and ends at 0.8. When the toolbar/menubar of the widget style has no gradient (like with the Breeze style, which is totally flat), no problem will be seen. However, once the toolbar/menubar has gradient, the result will be unnatural. This screenshot is taken with a Kvantum theme (please focus your eyes on the middle part):

![bad](https://user-images.githubusercontent.com/981076/42995355-e575ad38-8c25-11e8-8fcd-98ddd704d6fe.png)

This problem can be easily fixed by ending the gradient at 1.0 in `breezedecoration.cpp`, in this way:
```c++
        // render a linear gradient on title area
        if( m_internalSettings->drawBackgroundGradient() )
        {

            QColor titleBarColor( this->titleBarColor() );
            titleBarColor.setAlpha( m_internalSettings->opacitySlider() * 2.55 );

            QLinearGradient gradient( 0, 0, 0, titleRect.height() );
            gradient.setColorAt(0.0, titleBarColor.lighter( 120 ) );
            gradient.setColorAt(1.0, titleBarColor);

            painter->setBrush(gradient);

        } else {
```
Please note that I removed the extra condition `c->isActive()` because it made the titlebar of inactive windows very ugly.

The following screenshot is taken after the change -- the total gradient is smooth now:

![good](https://user-images.githubusercontent.com/981076/42995542-609d03e4-8c26-11e8-9b01-2b4a8f29f85c.png)

I think the issue is caused by too much focusing on the Breeze widget style and forgetting the obvious. I preferred to report the problem here and not at the KDE bug tracker because I use your decoration instead the Breeze decoration.

**Comment by alex47** [comment]
The only difference between BreezeBlurred and Breeze is the option to change the opacity. I see you use it with opaque setting. Does the problem happen when you set opacity to 75%? 50%?
The problem clearly lies with the Breeze decoration theme, not mine. Please report a bug in https://bugs.kde.org/enter_bug.cgi?product=Breeze
Once it's fixed in master, I'll rebase my fork on master.
I can see you fixed it for yourself so at least it's not a burning issue for you.

**Comment by tsujan** [comment]
> The problem clearly lies with the Breeze decoration theme, not mine.

That's right and I said the same thing above -- even in the title.

> Please report a bug in ...

I also told why I won't do so ;)

> I can see you fixed it for yourself so at least it's not a burning issue for you.

That's right; I fixed it for myself but wanted to explain the issue and share its solution.

I understand that you prefer your program not to have any difference from Breeze except for translucency+blurring and I respect your choice. Feel free to close this.

**Comment by alex47** [comment]
Thanks for understanding.
I personally disable the gradient as soon as I install Plasma, so I never noticed it.
And there will always be edge cases that break something...

**Comment by tsujan** [comment]
It was only a suggestion and I didn't want you to do something you didn't like. As programmer, I don't want that for myself either; so, I completely understand it :)
